### ISSUE TITLE
conditional model

### ISSUE THREAD

**Issue by Kee-Qin** [Zehui127/Latent-DNA-Diffusion#7]
I would like to express my sincere gratitude for your recent series of remarkable works. I am a student in the Department of Biostatistics and a beginner in diffusion models. To deepen my understanding of latent diffusion models (LDM), I have been studying your code. In your paper DiscDiff: Latent Diffusion Model for DNA Sequence Generation, you mentioned that the current diffusion model is a conditional model. However, the provided code appears to be for an unconditional model. I wanted to clarify: to achieve specific generation for the 15 species mentioned in the paper, should we modify the UNet2DModel in diffusers to UNet2DConditionModel, or will the code for conditional generation be updated in the future?

Apologies if this question seems a bit naive, but I am genuinely looking forward to your guidance. Thank you in advance for your time and assistance!

**Comment by Zehui127** [comment]
Hello @Kee-Qin ,

We will release the code. This repo is for the workshop paper initially, so the unconditional version of the model is sufficient for reproducing the results. Now, we have a follow-up work  [Paper Link](https://arxiv.org/abs/2410.21345) which will be presented in NeurIPS 2024. We will release the code around the neurIPS conference 2024 (in about 20 days) in the this new repo https://github.com/Zehui127/Absorb-Escape

The delay is because of the new version of the paper contains multiple systems, including the species conditioned DiscDiff.

**Comment by Kee-Qin** [comment]
Thank You for Your Kind Response
